// Сгенерировано `pnpm icons:build` из src/icons/svg. Руками не править.

/**
 * Публичный вход в набор иконок. Экспорты именованные и пофайловые —
 * реестра `name -> компонент` здесь намеренно нет: он утащил бы в бандл
 * все иконки сразу и убил tree-shaking.
 */

export { ArrowBackOutlineIcon } from './components/ArrowBackOutlineIcon'
export { ArrowForwardOutlineIcon } from './components/ArrowForwardOutlineIcon'
export { ArrowIosBackIcon } from './components/ArrowIosBackIcon'
export { ArrowIosBackOutlineIcon } from './components/ArrowIosBackOutlineIcon'
export { ArrowIosDownOutlineIcon } from './components/ArrowIosDownOutlineIcon'
export { ArrowIosForwardIcon } from './components/ArrowIosForwardIcon'
export { ArrowIosForwardOutlineIcon } from './components/ArrowIosForwardOutlineIcon'
export { ArrowIosUpIcon } from './components/ArrowIosUpIcon'
export { BellFillIcon } from './components/BellFillIcon'
export { BellOutlineIcon } from './components/BellOutlineIcon'
export { BlockIcon } from './components/BlockIcon'
export { BookmarkIcon } from './components/BookmarkIcon'
export { BookmarkOutlineIcon } from './components/BookmarkOutlineIcon'
export { CalendarIcon } from './components/CalendarIcon'
export { CalendarOutlineIcon } from './components/CalendarOutlineIcon'
export { CheckmarkOutlineIcon } from './components/CheckmarkOutlineIcon'
export { CloseIcon } from './components/CloseIcon'
export { CloseOutlineIcon } from './components/CloseOutlineIcon'
export { ColorPaletteOutlineIcon } from './components/ColorPaletteOutlineIcon'
export { CopyIcon } from './components/CopyIcon'
export { CopyOutlineIcon } from './components/CopyOutlineIcon'
export { CreditCardIcon } from './components/CreditCardIcon'
export { CreditCardOutlineIcon } from './components/CreditCardOutlineIcon'
export { DoneAllOutlineIcon } from './components/DoneAllOutlineIcon'
export { Edit2Icon } from './components/Edit2Icon'
export { Edit2OutlineIcon } from './components/Edit2OutlineIcon'
export { EmailIcon } from './components/EmailIcon'
export { EmailOutlineIcon } from './components/EmailOutlineIcon'
export { ExpandIcon } from './components/ExpandIcon'
export { ExpandOutlineIcon } from './components/ExpandOutlineIcon'
export { EyeIcon } from './components/EyeIcon'
export { EyeOffIcon } from './components/EyeOffIcon'
export { EyeOffOutlineIcon } from './components/EyeOffOutlineIcon'
export { EyeOutlineIcon } from './components/EyeOutlineIcon'
export { FacebookIcon } from './components/FacebookIcon'
export { FlagRuIcon } from './components/FlagRuIcon'
export { FlagUkIcon } from './components/FlagUkIcon'
export { GithubIcon } from './components/GithubIcon'
export { GoogleIcon } from './components/GoogleIcon'
export { HeartIcon } from './components/HeartIcon'
export { HeartOutlineIcon } from './components/HeartOutlineIcon'
export { HomeIcon } from './components/HomeIcon'
export { HomeOutlineIcon } from './components/HomeOutlineIcon'
export { ImageIcon } from './components/ImageIcon'
export { ImageOutlineIcon } from './components/ImageOutlineIcon'
export { LayersIcon } from './components/LayersIcon'
export { LayersOutlineIcon } from './components/LayersOutlineIcon'
export { LogOutIcon } from './components/LogOutIcon'
export { LogOutOutlineIcon } from './components/LogOutOutlineIcon'
export { MaximizeIcon } from './components/MaximizeIcon'
export { MaximizeOutlineIcon } from './components/MaximizeOutlineIcon'
export { MenuOutlineIcon } from './components/MenuOutlineIcon'
export { MessageCircleIcon } from './components/MessageCircleIcon'
export { MessageCircleOutlineIcon } from './components/MessageCircleOutlineIcon'
export { MicIcon } from './components/MicIcon'
export { MicOutlineIcon } from './components/MicOutlineIcon'
export { MoreHorizontalIcon } from './components/MoreHorizontalIcon'
export { MoreHorizontalOutlineIcon } from './components/MoreHorizontalOutlineIcon'
export { PaidIcon } from './components/PaidIcon'
export { PaperPlaneIcon } from './components/PaperPlaneIcon'
export { PaperPlaneOutlineIcon } from './components/PaperPlaneOutlineIcon'
export { PauseCircleIcon } from './components/PauseCircleIcon'
export { PauseCircleOutlineIcon } from './components/PauseCircleOutlineIcon'
export { PaypalIcon } from './components/PaypalIcon'
export { PersonAddIcon } from './components/PersonAddIcon'
export { PersonAddOutlineIcon } from './components/PersonAddOutlineIcon'
export { PersonIcon } from './components/PersonIcon'
export { PersonOutlineIcon } from './components/PersonOutlineIcon'
export { PersonRemoveIcon } from './components/PersonRemoveIcon'
export { PersonRemoveOutlineIcon } from './components/PersonRemoveOutlineIcon'
export { PinIcon } from './components/PinIcon'
export { PinOutlineIcon } from './components/PinOutlineIcon'
export { PlayCircleIcon } from './components/PlayCircleIcon'
export { PlayCircleOutlineIcon } from './components/PlayCircleOutlineIcon'
export { PlusCircleIcon } from './components/PlusCircleIcon'
export { PlusCircleOutlineIcon } from './components/PlusCircleOutlineIcon'
export { PlusSquareIcon } from './components/PlusSquareIcon'
export { PlusSquareOutlineIcon } from './components/PlusSquareOutlineIcon'
export { RadioButtonCheckedIcon } from './components/RadioButtonCheckedIcon'
export { RadioButtonUncheckedIcon } from './components/RadioButtonUncheckedIcon'
export { RecaptchaLogoIcon } from './components/RecaptchaLogoIcon'
export { SearchIcon } from './components/SearchIcon'
export { SearchOutlineIcon } from './components/SearchOutlineIcon'
export { SettingsIcon } from './components/SettingsIcon'
export { SettingsOutlineIcon } from './components/SettingsOutlineIcon'
export { StripeIcon } from './components/StripeIcon'
export { TrashIcon } from './components/TrashIcon'
export { TrashOutlineIcon } from './components/TrashOutlineIcon'
export { TrendingUpIcon } from './components/TrendingUpIcon'
export { TrendingUpOutlineIcon } from './components/TrendingUpOutlineIcon'
export type { IconProps } from './types'

/**
 * Имена всех иконок набора.
 *
 * Нужен там, где иконка выбирается из данных, а не пишется в коде:
 * проп вида `icon: IconName` или значение из ответа API. Генерируется вместе
 * с компонентами, поэтому не может разъехаться с содержимым папки.
 */
export type IconName =
  | 'arrow-back-outline'
  | 'arrow-forward-outline'
  | 'arrow-ios-back-outline'
  | 'arrow-ios-back'
  | 'arrow-ios-down-outline'
  | 'arrow-ios-forward-outline'
  | 'arrow-ios-forward'
  | 'arrow-ios-up'
  | 'bell-fill'
  | 'bell-outline'
  | 'block'
  | 'bookmark-outline'
  | 'bookmark'
  | 'calendar-outline'
  | 'calendar'
  | 'checkmark-outline'
  | 'close-outline'
  | 'close'
  | 'color-palette-outline'
  | 'copy-outline'
  | 'copy'
  | 'credit-card-outline'
  | 'credit-card'
  | 'done-all-outline'
  | 'edit-2-outline'
  | 'edit-2'
  | 'email-outline'
  | 'email'
  | 'expand-outline'
  | 'expand'
  | 'eye-off-outline'
  | 'eye-off'
  | 'eye-outline'
  | 'eye'
  | 'facebook'
  | 'flag-ru'
  | 'flag-uk'
  | 'github'
  | 'google'
  | 'heart-outline'
  | 'heart'
  | 'home-outline'
  | 'home'
  | 'image-outline'
  | 'image'
  | 'layers-outline'
  | 'layers'
  | 'log-out-outline'
  | 'log-out'
  | 'maximize-outline'
  | 'maximize'
  | 'menu-outline'
  | 'message-circle-outline'
  | 'message-circle'
  | 'mic-outline'
  | 'mic'
  | 'more-horizontal-outline'
  | 'more-horizontal'
  | 'paid'
  | 'paper-plane-outline'
  | 'paper-plane'
  | 'pause-circle-outline'
  | 'pause-circle'
  | 'paypal'
  | 'person-add-outline'
  | 'person-add'
  | 'person-outline'
  | 'person-remove-outline'
  | 'person-remove'
  | 'person'
  | 'pin-outline'
  | 'pin'
  | 'play-circle-outline'
  | 'play-circle'
  | 'plus-circle-outline'
  | 'plus-circle'
  | 'plus-square-outline'
  | 'plus-square'
  | 'radio-button-checked'
  | 'radio-button-unchecked'
  | 'recaptcha-logo'
  | 'search-outline'
  | 'search'
  | 'settings-outline'
  | 'settings'
  | 'stripe'
  | 'trash-outline'
  | 'trash'
  | 'trending-up-outline'
  | 'trending-up'
