// Сгенерировано `pnpm icons:build` из src/icons/svg. Руками не править.

/**
 * Публичный вход в набор иконок. Экспорты именованные и пофайловые —
 * реестра `name -> компонент` здесь намеренно нет: он утащил бы в бандл
 * все иконки сразу и убил tree-shaking.
 */

export { ArrowBackOutlineIcon } from './components/ArrowBackOutlineIcon.js'
export { ArrowForwardOutlineIcon } from './components/ArrowForwardOutlineIcon.js'
export { ArrowIosBackIcon } from './components/ArrowIosBackIcon.js'
export { ArrowIosBackOutlineIcon } from './components/ArrowIosBackOutlineIcon.js'
export { ArrowIosDownOutlineIcon } from './components/ArrowIosDownOutlineIcon.js'
export { ArrowIosForwardIcon } from './components/ArrowIosForwardIcon.js'
export { ArrowIosForwardOutlineIcon } from './components/ArrowIosForwardOutlineIcon.js'
export { ArrowIosUpIcon } from './components/ArrowIosUpIcon.js'
export { BellFillIcon } from './components/BellFillIcon.js'
export { BellOutlineIcon } from './components/BellOutlineIcon.js'
export { BlockIcon } from './components/BlockIcon.js'
export { BookmarkIcon } from './components/BookmarkIcon.js'
export { BookmarkOutlineIcon } from './components/BookmarkOutlineIcon.js'
export { CalendarIcon } from './components/CalendarIcon.js'
export { CalendarOutlineIcon } from './components/CalendarOutlineIcon.js'
export { CheckmarkOutlineIcon } from './components/CheckmarkOutlineIcon.js'
export { CloseIcon } from './components/CloseIcon.js'
export { CloseOutlineIcon } from './components/CloseOutlineIcon.js'
export { ColorPaletteOutlineIcon } from './components/ColorPaletteOutlineIcon.js'
export { CopyIcon } from './components/CopyIcon.js'
export { CopyOutlineIcon } from './components/CopyOutlineIcon.js'
export { CreditCardIcon } from './components/CreditCardIcon.js'
export { CreditCardOutlineIcon } from './components/CreditCardOutlineIcon.js'
export { DoneAllOutlineIcon } from './components/DoneAllOutlineIcon.js'
export { Edit2Icon } from './components/Edit2Icon.js'
export { Edit2OutlineIcon } from './components/Edit2OutlineIcon.js'
export { EmailIcon } from './components/EmailIcon.js'
export { EmailOutlineIcon } from './components/EmailOutlineIcon.js'
export { ExpandIcon } from './components/ExpandIcon.js'
export { ExpandOutlineIcon } from './components/ExpandOutlineIcon.js'
export { EyeIcon } from './components/EyeIcon.js'
export { EyeOffIcon } from './components/EyeOffIcon.js'
export { EyeOffOutlineIcon } from './components/EyeOffOutlineIcon.js'
export { EyeOutlineIcon } from './components/EyeOutlineIcon.js'
export { FacebookIcon } from './components/FacebookIcon.js'
export { FlagRuIcon } from './components/FlagRuIcon.js'
export { FlagUkIcon } from './components/FlagUkIcon.js'
export { GithubIcon } from './components/GithubIcon.js'
export { GoogleIcon } from './components/GoogleIcon.js'
export { HeartIcon } from './components/HeartIcon.js'
export { HeartOutlineIcon } from './components/HeartOutlineIcon.js'
export { HomeIcon } from './components/HomeIcon.js'
export { HomeOutlineIcon } from './components/HomeOutlineIcon.js'
export { ImageIcon } from './components/ImageIcon.js'
export { ImageOutlineIcon } from './components/ImageOutlineIcon.js'
export { LayersIcon } from './components/LayersIcon.js'
export { LayersOutlineIcon } from './components/LayersOutlineIcon.js'
export { LogOutIcon } from './components/LogOutIcon.js'
export { LogOutOutlineIcon } from './components/LogOutOutlineIcon.js'
export { MaximizeIcon } from './components/MaximizeIcon.js'
export { MaximizeOutlineIcon } from './components/MaximizeOutlineIcon.js'
export { MenuOutlineIcon } from './components/MenuOutlineIcon.js'
export { MessageCircleIcon } from './components/MessageCircleIcon.js'
export { MessageCircleOutlineIcon } from './components/MessageCircleOutlineIcon.js'
export { MicIcon } from './components/MicIcon.js'
export { MicOutlineIcon } from './components/MicOutlineIcon.js'
export { MoreHorizontalIcon } from './components/MoreHorizontalIcon.js'
export { MoreHorizontalOutlineIcon } from './components/MoreHorizontalOutlineIcon.js'
export { PaidIcon } from './components/PaidIcon.js'
export { PaperPlaneIcon } from './components/PaperPlaneIcon.js'
export { PaperPlaneOutlineIcon } from './components/PaperPlaneOutlineIcon.js'
export { PauseCircleIcon } from './components/PauseCircleIcon.js'
export { PauseCircleOutlineIcon } from './components/PauseCircleOutlineIcon.js'
export { PaypalIcon } from './components/PaypalIcon.js'
export { PersonAddIcon } from './components/PersonAddIcon.js'
export { PersonAddOutlineIcon } from './components/PersonAddOutlineIcon.js'
export { PersonIcon } from './components/PersonIcon.js'
export { PersonOutlineIcon } from './components/PersonOutlineIcon.js'
export { PersonRemoveIcon } from './components/PersonRemoveIcon.js'
export { PersonRemoveOutlineIcon } from './components/PersonRemoveOutlineIcon.js'
export { PinIcon } from './components/PinIcon.js'
export { PinOutlineIcon } from './components/PinOutlineIcon.js'
export { PlayCircleIcon } from './components/PlayCircleIcon.js'
export { PlayCircleOutlineIcon } from './components/PlayCircleOutlineIcon.js'
export { PlusCircleIcon } from './components/PlusCircleIcon.js'
export { PlusCircleOutlineIcon } from './components/PlusCircleOutlineIcon.js'
export { PlusSquareIcon } from './components/PlusSquareIcon.js'
export { PlusSquareOutlineIcon } from './components/PlusSquareOutlineIcon.js'
export { RadioButtonCheckedIcon } from './components/RadioButtonCheckedIcon.js'
export { RadioButtonUncheckedIcon } from './components/RadioButtonUncheckedIcon.js'
export { RecaptchaLogoIcon } from './components/RecaptchaLogoIcon.js'
export { SearchIcon } from './components/SearchIcon.js'
export { SearchOutlineIcon } from './components/SearchOutlineIcon.js'
export { SettingsIcon } from './components/SettingsIcon.js'
export { SettingsOutlineIcon } from './components/SettingsOutlineIcon.js'
export { StripeIcon } from './components/StripeIcon.js'
export { TrashIcon } from './components/TrashIcon.js'
export { TrashOutlineIcon } from './components/TrashOutlineIcon.js'
export { TrendingUpIcon } from './components/TrendingUpIcon.js'
export { TrendingUpOutlineIcon } from './components/TrendingUpOutlineIcon.js'
export type { IconProps } from './types.js'

/**
 * Имена всех иконок набора.
 *
 * Нужен там, где иконка выбирается из данных, а не пишется в коде:
 * проп вида `icon: IconName` или значение из ответа API. Генерируется вместе
 * с компонентами, поэтому не может разъехаться с содержимым папки.
 */
export type IconName =
  | 'arrow-back-outline'
  | 'arrow-forward-outline'
  | 'arrow-ios-back-outline'
  | 'arrow-ios-back'
  | 'arrow-ios-down-outline'
  | 'arrow-ios-forward-outline'
  | 'arrow-ios-forward'
  | 'arrow-ios-up'
  | 'bell-fill'
  | 'bell-outline'
  | 'block'
  | 'bookmark-outline'
  | 'bookmark'
  | 'calendar-outline'
  | 'calendar'
  | 'checkmark-outline'
  | 'close-outline'
  | 'close'
  | 'color-palette-outline'
  | 'copy-outline'
  | 'copy'
  | 'credit-card-outline'
  | 'credit-card'
  | 'done-all-outline'
  | 'edit-2-outline'
  | 'edit-2'
  | 'email-outline'
  | 'email'
  | 'expand-outline'
  | 'expand'
  | 'eye-off-outline'
  | 'eye-off'
  | 'eye-outline'
  | 'eye'
  | 'facebook'
  | 'flag-ru'
  | 'flag-uk'
  | 'github'
  | 'google'
  | 'heart-outline'
  | 'heart'
  | 'home-outline'
  | 'home'
  | 'image-outline'
  | 'image'
  | 'layers-outline'
  | 'layers'
  | 'log-out-outline'
  | 'log-out'
  | 'maximize-outline'
  | 'maximize'
  | 'menu-outline'
  | 'message-circle-outline'
  | 'message-circle'
  | 'mic-outline'
  | 'mic'
  | 'more-horizontal-outline'
  | 'more-horizontal'
  | 'paid'
  | 'paper-plane-outline'
  | 'paper-plane'
  | 'pause-circle-outline'
  | 'pause-circle'
  | 'paypal'
  | 'person-add-outline'
  | 'person-add'
  | 'person-outline'
  | 'person-remove-outline'
  | 'person-remove'
  | 'person'
  | 'pin-outline'
  | 'pin'
  | 'play-circle-outline'
  | 'play-circle'
  | 'plus-circle-outline'
  | 'plus-circle'
  | 'plus-square-outline'
  | 'plus-square'
  | 'radio-button-checked'
  | 'radio-button-unchecked'
  | 'recaptcha-logo'
  | 'search-outline'
  | 'search'
  | 'settings-outline'
  | 'settings'
  | 'stripe'
  | 'trash-outline'
  | 'trash'
  | 'trending-up-outline'
  | 'trending-up'
