// Баррель компонентов. Реэкспорт пофайловый — preserveModules оставляет
// по модулю на компонент, поэтому tree-shaking через баррель не ломается.
export * from './alert/index.js'
export * from './button/index.js'
export * from './card/index.js'
export * from './checkbox/index.js'
export * from './confirm-dialog/index.js'
export * from './date-picker/index.js'
export * from './dropdown-menu/index.js'
export * from './input/index.js'
export * from './modal/index.js'
export * from './pagination/index.js'
export * from './radio-group/index.js'
export * from './recaptcha/index.js'
export * from './scroll/index.js'
export * from './select/index.js'
export * from './tabs/index.js'
export * from './textarea/index.js'
